services:
  - name: frontend
    buildCommand: npm install 
    startCommand: npm run dev
  - name: backend
    buildCommand: npm run build 
    startCommand: npm run server
  - name: admin
    buildCommand: npm install 
    startCommand: npm run dev
  - name: modelAI
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload --port 4040
